title: Yuriy Romadin
email: yuriy@romadin.eu
description: >- # this means to ignore newlines until "baseurl:"
  Web developer and problem solver
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yuriyromadin
github_username:  yuriyromadin
facebook_username:  yuriyromadin
author: Yuriy Romadin

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-clean-blog
remote_theme: blackrockdigital/startbootstrap-clean-blog-jekyll
plugins:
  - jekyll-feed

sass:
    sass_dir: assets/css/_sass
